# Generated by Django 6.0.3 on 2026-03-15 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.moduloprueba'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_dificultad', models.CharField(choices=[('Facil', 'Fácil'), ('Medio', 'Medio'), ('Dificil', 'Difícil')], max_length=15)),
                ('contexto_texto', models.TextField(blank=True, null=True)),
                ('contexto_imagen', models.ImageField(blank=True, null=True, upload_to='preguntas/contextos/')),
                ('enunciado', models.TextField()),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('limite_palabras', models.IntegerField(blank=True, default=3000, null=True)),
                ('rubrica_evaluacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicada', 'Publicada'), ('Archivada', 'Archivada')], default='Borrador', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.categoria')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.competencia')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.moduloprueba')),
                ('version_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='preguntas/opciones/')),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluaciones.pregunta')),
            ],
        ),
    ]
