# Generated by Django 6.0.3 on 2026-03-15 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tiempo_minutos', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('mostrar_resultados_inmediatos', models.BooleanField(default=False)),
                ('es_simulacro_oficial', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Borrador', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programas_destino', models.ManyToManyField(related_name='examenes_asignados', to='users.programaacademico')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_preguntas', models.IntegerField()),
                ('nivel_dificultad', models.CharField(choices=[('Facil', 'Fácil'), ('Medio', 'Medio'), ('Dificil', 'Difícil'), ('Balanceada', 'Balanceada')], default='Balanceada', max_length=15)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.categoria')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='evaluaciones.plantillaexamen')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.moduloprueba')),
            ],
        ),
    ]
