# Generated by Django 6.0.3 on 2026-03-15 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_plantillaexamen_reglaexamen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('En Progreso', 'En Progreso'), ('Pendiente Calificacion', 'Pendiente Calificacion'), ('Finalizado', 'Finalizado')], default='En Progreso', max_length=30)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to=settings.AUTH_USER_MODEL)),
                ('plantilla_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.plantillaexamen')),
            ],
        ),
        migrations.CreateModel(
            name='IntentoModulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado')], default='Pendiente', max_length=20)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='evaluaciones.intentoexamen')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.moduloprueba')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto_respuesta_abierta', models.TextField(blank=True, null=True)),
                ('marcada_para_revision', models.BooleanField(default=False)),
                ('puntaje_calificado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.intentoexamen')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.pregunta')),
            ],
        ),
    ]
