# Generated by Django 6.0.3 on 2026-03-15 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_intentoexamen_intentomodulo_respuestaestudiante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaestudiante',
            name='evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ensayos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
