# Generated by Django 6.0.3 on 2026-03-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_refactor_competencia_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='opciones/'),
        ),
    ]
