# Generated by Django 6.0.3 on 2026-03-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0006_alter_opcionrespuesta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillaexamen',
            name='estado',
            field=models.CharField(
                choices=[
                    ('Borrador', 'Borrador'),
                    ('Activo', 'Activo'),
                    ('Inactivo', 'Inactivo'),
                    ('Archivado', 'Archivado'),
                ],
                default='Borrador',
                max_length=15,
            ),
        ),
    ]
