# Generated by Django 6.0.3 on 2026-03-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_alter_plantillaexamen_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoexamen',
            name='plan_estudio_ia',
            field=models.TextField(blank=True, help_text='Plan de estudio generado por IA en formato Markdown', null=True),
        ),
    ]
