# Generated by Django 6.0.3 on 2026-03-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0008_intentoexamen_plan_estudio_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='lote_id',
            field=models.UUIDField(blank=True, help_text='ID de la carga masiva que origino esta pregunta', null=True),
        ),
    ]
