# Generated by Django 6.0.3 on 2026-03-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0009_pregunta_lote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='codigo_latex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='imagen_grafica',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas_graficas/'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='soporte_multimedia',
            field=models.CharField(choices=[('NINGUNO', 'Ninguno'), ('IMAGEN', 'Imagen'), ('LATEX', 'LaTeX')], default='NINGUNO', max_length=10),
        ),
    ]
