# Generated by Django 6.0.3 on 2026-04-04 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0010_pregunta_codigo_latex_pregunta_imagen_grafica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='intentoexamen',
            constraint=models.UniqueConstraint(fields=('estudiante', 'plantilla_examen'), name='unico_intento_por_examen'),
        ),
    ]
