# Generated by Django 6.0.3 on 2026-04-05 02:31

import evaluaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0012_plantillaexamen_creado_por_pregunta_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=evaluaciones.models.generar_ruta_imagen_segura),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='contexto_imagen',
            field=models.ImageField(blank=True, null=True, upload_to=evaluaciones.models.generar_ruta_imagen_segura),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_grafica',
            field=models.ImageField(blank=True, null=True, upload_to=evaluaciones.models.generar_ruta_imagen_segura),
        ),
    ]
