# Generated by Django 6.0.3 on 2026-05-21 16:27

import evaluaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0016_sanitize_enunciado_normalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='codigo_latex_md5',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_grafica',
            field=models.FileField(blank=True, null=True, upload_to=evaluaciones.models.generar_ruta_imagen_segura),
        ),
    ]
