# Generated by Django 6.0.3 on 2026-03-18 14:59

from django.db import migrations, models


def poblar_roles_existentes(apps, schema_editor):
    del schema_editor
    Usuario = apps.get_model('users', 'Usuario')
    Usuario.objects.filter(is_staff=True).update(rol='ADMIN')
    Usuario.objects.filter(is_staff=False).update(rol='ESTUDIANTE')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=20),
        ),
        migrations.RunPython(poblar_roles_existentes, migrations.RunPython.noop),
    ]
