# Generated by Django 6.0.3 on 2026-03-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='semestre_actual',
            field=models.IntegerField(blank=True, help_text='Semestre que cursa actualmente (ej. 1 al 10)', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=2, null=True),
        ),
    ]
