# Generated by Codex on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_usuario_semestre_actual_alter_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(
                choices=[
                    ('ADMIN', 'Administrador'),
                    ('PROFESOR', 'Profesor'),
                    ('ESTUDIANTE', 'Estudiante'),
                ],
                default='ESTUDIANTE',
                max_length=20,
            ),
        ),
    ]
